### PR TITLE
[HW1] chilin0525 v.01 attempt

### PR DESCRIPTION
**Pull request by chilin0525**
---
A good PR should include the following parts:

- [X] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by yungyuc** [comment]
@q40603 This PR doesn't trigger CI.  It happens again.

**Comment by yungyuc** [comment]
@chilin0525 Can you push an additional change to the branch?  Perhaps that can trigger the CI for you.

**Comment by chilin0525** [comment]
@yungyuc  Is CI functioning properly now?

**Comment by yungyuc** [comment]
@chilin0525 It kicks in.  Thanks.  It seems changing the destination branch alone doesn't trigger the run.

**Pull request merged**
