### PR TITLE
Eric860730 hw4 attempt1

### PR DESCRIPTION
**Pull request by Eric860730**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [x] passing tests/CI

### CODE REVIEW

**Comment by Eric860730** [comment]
@q40603 @yungyuc Hi, teacher and TA, I have some questions about hw4.
1. First of all, I want to know if I don’t define a move constructor, why can’t I pass the verification?https://github.com/Eric860730/nsdhw_21au/blob/a540ab400c953932631ef3d85ba92b9c08ba2ab6/hw4/Eric860730/include/_GEMM.hpp#L33~L39
As a result, some errors are shown in the figure below
Screenshot from 2021-11-29 20-00-41
2. And another question is about pybind11. In the beginning, I separate pybind11 at another file Matrix_pybind.cpp and change Makefile by add Matrix_pybind.cpp after _GEMM.cpp
pybind code: https://github.com/Eric860730/nsdhw_21au/blob/a540ab400c953932631ef3d85ba92b9c08ba2ab6/hw4/Eric860730/lib/_GEMM.cpp#L129-L153
Makefile:
https://github.com/Eric860730/nsdhw_21au/blob/a540ab400c953932631ef3d85ba92b9c08ba2ab6/hw4/Eric860730/Makefile#L23
I can compile my code and generate *.so file, but my allocator can not work successfully.
Screenshot from 2021-11-29 20-11-52
Finally I put my Matrix_pybind.cpp in my lib/_GEMM.cpp and successfully passed the validation, but I don't know where I was wrong.
Thank you for reading my long question.:sweat_smile:

**Comment by yungyuc** [comment]
> @q40603 @yungyuc Hi, teacher and TA, I have some questions about hw4.
> 
> 1. First of all, I want to know if I don’t define a move constructor, why can’t I pass the verification?https://github.com/Eric860730/nsdhw_21au/blob/a540ab400c953932631ef3d85ba92b9c08ba2ab6/hw4/Eric860730/include/_GEMM.hpp#L33~L39
>    As a result, some errors are shown in the figure below
>    Screenshot from 2021-11-29 20-00-41
> 2. And another question is about pybind11. In the beginning, I separate pybind11 at another file Matrix_pybind.cpp and change Makefile by add Matrix_pybind.cpp after _GEMM.cpp
>    pybind code: https://github.com/Eric860730/nsdhw_21au/blob/a540ab400c953932631ef3d85ba92b9c08ba2ab6/hw4/Eric860730/lib/_GEMM.cpp#L129-L153
>    Makefile:
>    https://github.com/Eric860730/nsdhw_21au/blob/a540ab400c953932631ef3d85ba92b9c08ba2ab6/hw4/Eric860730/Makefile#L23
>    I can compile my code and generate *.so file, but my allocator can not work successfully.
>    Screenshot from 2021-11-29 20-11-52
>    Finally I put my Matrix_pybind.cpp in my lib/_GEMM.cpp and successfully passed the validation, but I don't know where I was wrong.
>    Thank you for reading my long question.😅

Could you please provide the Python stack trace (traceback) of the failures?  Then you can pin-point which assersion went wrong.

And it is much better to copy the texts themselves rather than pasting images, which are one of the worst ways to share code.

**Comment by Eric860730** [comment]
Complete fault information for question 1. Command: ```$ ../validate```
```python3=
=== FAILURES ===
__ GradingTest.test_match_naive_mkl __
self = <validate.GradingTest testMethod=test_match_naive_mkl>

    def test_match_naive_mkl(self):
    
        self.assertEqual(0, _matrix.bytes())
    
        size = 100
        mat1, mat2, *_ = self.make_matrices(size)
        self.assertEqual(3*8 * size*size, _matrix.bytes())
        base_alloc = _matrix.allocated()
        base_dealloc = _matrix.deallocated()
    
        ret_naive = _matrix.multiply_naive(mat1, mat2)
        ret_mkl = _matrix.multiply_mkl(mat1, mat2)
    
        self.assertEqual(size, ret_naive.nrow)
        self.assertEqual(size, ret_naive.ncol)
        self.assertEqual(size, ret_mkl.nrow)
        self.assertEqual(size, ret_mkl.ncol)
    
        for i in range(ret_naive.nrow):
            for j in range(ret_naive.ncol):
                self.assertNotEqual(mat1[i,j], ret_mkl[i,j])
                self.assertEqual(ret_naive[i,j], ret_mkl[i,j])
    
        self.assertEqual(5*8 * size*size, _matrix.bytes())
>       self.assertEqual(base_alloc + 2*8 * size*size, _matrix.allocated())
E       AssertionError: 640000 != 800000

../validate.py:137: AssertionError
__ GradingTest.test_memory __

self = <validate.GradingTest testMethod=test_memory>

    def test_memory(self):
    
>       self.assertEqual(0, _matrix.bytes())
E       AssertionError: 0 != 400000

../validate.py:169: AssertionError
__ GradingTest.test_zero ___
self = <validate.GradingTest testMethod=test_zero>

    def test_zero(self):
    
>       self.assertEqual(0, _matrix.bytes())
E       AssertionError: 0 != 400000

../validate.py:142: AssertionError
=== short test summary info ===
FAILED ../validate.py::GradingTest::test_match_naive_mkl - AssertionError: 640000 != 800000
FAILED ../validate.py::GradingTest::test_memory - AssertionError: 0 != 400000
FAILED ../validate.py::GradingTest::test_zero - AssertionError: 0 != 400000
=== 3 failed, 1 passed in 0.09s ===
```
Complete fault information for question 2. Command: ```$ ../validate```
```python3=
=== FAILURES ===
___ GradingTest.test_basic ____
self = <validate.GradingTest testMethod=test_basic>

    def test_basic(self):
    
        self.assertEqual(0, _matrix.bytes())
    
        size = 100
        mat1, mat2, mat3, *_ = self.make_matrices(size)
>       self.assertEqual(3*8 * size*size, _matrix.bytes())
E       AssertionError: 240000 != 0

../validate.py:84: AssertionError
___ GradingTest.test_match_naive_mkl ___

self = <validate.GradingTest testMethod=test_match_naive_mkl>

    def test_match_naive_mkl(self):
    
        self.assertEqual(0, _matrix.bytes())
    
        size = 100
        mat1, mat2, *_ = self.make_matrices(size)
>       self.assertEqual(3*8 * size*size, _matrix.bytes())
E       AssertionError: 240000 != 0

../validate.py:119: AssertionError
___ GradingTest.test_memory ___
self = <validate.GradingTest testMethod=test_memory>

    def test_memory(self):
    
        self.assertEqual(0, _matrix.bytes())
        base_alloc = _matrix.allocated()
        base_dealloc = _matrix.deallocated()
    
        size = 100
        mat1, mat2, mat3, *_ = self.make_matrices(size)
>       self.assertEqual(3*8 * size*size, _matrix.bytes())
E       AssertionError: 240000 != 0

../validate.py:175: AssertionError
___ GradingTest.test_zero ___

self = <validate.GradingTest testMethod=test_zero>

    def test_zero(self):
    
        self.assertEqual(0, _matrix.bytes())
    
        size = 200
        mat1, mat2, mat3, *_ = self.make_matrices(size)
>       self.assertEqual(3*8 * size*size, _matrix.bytes())
E       AssertionError: 960000 != 0

../validate.py:146: AssertionError
=== short test summary info ===
FAILED ../validate.py::GradingTest::test_basic - AssertionError: 240000 != 0
FAILED ../validate.py::GradingTest::test_match_naive_mkl - AssertionError: 240000 != 0
FAILED ../validate.py::GradingTest::test_memory - AssertionError: 240000 != 0
FAILED ../validate.py::GradingTest::test_zero - AssertionError: 960000 != 0
=== 4 failed in 0.10s ===
*** validation failed
```

Sorry to paste the failed message in a bad way.

**Comment by yungyuc** [comment]
> Complete fault information for question 1. Command: `$ ../validate`
> 
> ```
> === FAILURES ===
> __ GradingTest.test_match_naive_mkl __
> self = <validate.GradingTest testMethod=test_match_naive_mkl>
> 
>     def test_match_naive_mkl(self):
>     
>         self.assertEqual(0, _matrix.bytes())
>     
>         size = 100
>         mat1, mat2, *_ = self.make_matrices(size)
>         self.assertEqual(3*8 * size*size, _matrix.bytes())
>         base_alloc = _matrix.allocated()
>         base_dealloc = _matrix.deallocated()
>     
> ```

There is not exception at this point.

> ```
>         ret_naive = _matrix.multiply_naive(mat1, mat2)
>         ret_mkl = _matrix.multiply_mkl(mat1, mat2)
>     
> ```

This calls into your code.

> ```
>         self.assertEqual(size, ret_naive.nrow)
>         self.assertEqual(size, ret_naive.ncol)
>         self.assertEqual(size, ret_mkl.nrow)
>         self.assertEqual(size, ret_mkl.ncol)
>     
>         for i in range(ret_naive.nrow):
>             for j in range(ret_naive.ncol):
>                 self.assertNotEqual(mat1[i,j], ret_mkl[i,j])
>                 self.assertEqual(ret_naive[i,j], ret_mkl[i,j])
>     
>         self.assertEqual(5*8 * size*size, _matrix.bytes())
> >       self.assertEqual(base_alloc + 2*8 * size*size, _matrix.allocated())
> E       AssertionError: 640000 != 800000
> 
> ../validate.py:137: AssertionError
> ```

I would think the implementation in your `multiply_naive()` and/or `multiply_mkl()` allocates different amount of memory depending on whether or not the move constructor is used.  To verify, you may insert the assersion at more locations and determine which function is the culprit.

After locating the function in question, you can make a debug build and use gdb/lldb (any debugger) to step into the C++ code, to see what really happens inside.

> ```
> __ GradingTest.test_memory __
> 
> self = <validate.GradingTest testMethod=test_memory>
> 
>     def test_memory(self):
>     
> >       self.assertEqual(0, _matrix.bytes())
> E       AssertionError: 0 != 400000
> 
> ../validate.py:169: AssertionError
> ```

This may be memory leak resulted from another test.  Maybe your code does not free memory in a correct way when the move constructor is not present.

> ```
> __ GradingTest.test_zero ___
> self = <validate.GradingTest testMethod=test_zero>
> 
>     def test_zero(self):
>     
> >       self.assertEqual(0, _matrix.bytes())
> E       AssertionError: 0 != 400000
> 
> ../validate.py:142: AssertionError
> ```

Ditto.

> ```
> === short test summary info ===
> FAILED ../validate.py::GradingTest::test_match_naive_mkl - AssertionError: 640000 != 800000
> FAILED ../validate.py::GradingTest::test_memory - AssertionError: 0 != 400000
> FAILED ../validate.py::GradingTest::test_zero - AssertionError: 0 != 400000
> === 3 failed, 1 passed in 0.09s ===
> ```
> 

The second problem looks like wrong reference to the byte counter.  Are you sure you have only one instance of the byte counter?

> Complete fault information for question 2. Command: `$ ../validate`
> 
> ```
> === FAILURES ===
> ___ GradingTest.test_basic ____
> self = <validate.GradingTest testMethod=test_basic>
> 
>     def test_basic(self):
>     
>         self.assertEqual(0, _matrix.bytes())
>     
>         size = 100
>         mat1, mat2, mat3, *_ = self.make_matrices(size)
> >       self.assertEqual(3*8 * size*size, _matrix.bytes())
> E       AssertionError: 240000 != 0
> 
> ../validate.py:84: AssertionError
> ___ GradingTest.test_match_naive_mkl ___
> 
> self = <validate.GradingTest testMethod=test_match_naive_mkl>
> 
>     def test_match_naive_mkl(self):
>     
>         self.assertEqual(0, _matrix.bytes())
>     
>         size = 100
>         mat1, mat2, *_ = self.make_matrices(size)
> >       self.assertEqual(3*8 * size*size, _matrix.bytes())
> E       AssertionError: 240000 != 0
> 
> ../validate.py:119: AssertionError
> ___ GradingTest.test_memory ___
> self = <validate.GradingTest testMethod=test_memory>
> 
>     def test_memory(self):
>     
>         self.assertEqual(0, _matrix.bytes())
>         base_alloc = _matrix.allocated()
>         base_dealloc = _matrix.deallocated()
>     
>         size = 100
>         mat1, mat2, mat3, *_ = self.make_matrices(size)
> >       self.assertEqual(3*8 * size*size, _matrix.bytes())
> E       AssertionError: 240000 != 0
> 
> ../validate.py:175: AssertionError
> ___ GradingTest.test_zero ___
> 
> self = <validate.GradingTest testMethod=test_zero>
> 
>     def test_zero(self):
>     
>         self.assertEqual(0, _matrix.bytes())
>     
>         size = 200
>         mat1, mat2, mat3, *_ = self.make_matrices(size)
> >       self.assertEqual(3*8 * size*size, _matrix.bytes())
> E       AssertionError: 960000 != 0
> 
> ../validate.py:146: AssertionError
> === short test summary info ===
> FAILED ../validate.py::GradingTest::test_basic - AssertionError: 240000 != 0
> FAILED ../validate.py::GradingTest::test_match_naive_mkl - AssertionError: 240000 != 0
> FAILED ../validate.py::GradingTest::test_memory - AssertionError: 240000 != 0
> FAILED ../validate.py::GradingTest::test_zero - AssertionError: 960000 != 0
> === 4 failed in 0.10s ===
> *** validation failed
> ```
> 
> Sorry to paste the failed message in a bad way.

**Comment by yungyuc** [comment]
@q40603 Feel free to merge once you finish grading.  @Eric860730 and I can continue discuss with the closed PR.  If necessary we can move the discussions elsewhere.

**Comment by yungyuc** [comment]
@Eric860730 Please let me know whether or not you have further questions?

**Comment by Eric860730** [comment]
@yungyuc Thank you teacher for your suggestion. But I am preparing for the next meeting. I will try it on Tuesday.

**Comment by Eric860730** [comment]
Q1
> I would think the implementation in your `multiply_naive()` and/or `multiply_mkl()` allocates different amount of memory depending on whether or not the move constructor is used. To verify, you may insert the assersion at more locations and determine which function is the culprit.
> 
> After locating the function in question, you can make a debug build and use gdb/lldb (any debugger) to step into the C++ code, to see what really happens inside.
> 
> >
I wrote a main function(same as the test function test_match_naive_mkl in the validate.py) to test the code running in a pure cpp file (not including pybind). I printed out the status of the matrix allocator and everything is correct(no matter with or without move constructor). Then I use gdb to check the status of matrix_allocator line by line, and the address of matrix_allocator has not changed. There seems to be nothing wrong in a pure cpp environment. Maybe the problem is pybind?

> This may be memory leak resulted from another test. Maybe your code does not free memory in a correct way when the move constructor is not present.
There is no problem in a pure cpp environment.

---
Q2
> The second problem looks like wrong reference to the byte counter. Are you sure you have only one instance of the byte counter?

Yes, I have only one instance of the byte counter. My global function name bytes() is the same as the member function bytes() in struct MyAllocator. I changed the name of my function, but got the same result. It seems that there is no problem, and I still can't guess where the problem might be.

**Comment by yungyuc** [comment]
> Q1
> 
> > I would think the implementation in your `multiply_naive()` and/or `multiply_mkl()` allocates different amount of memory depending on whether or not the move constructor is used. To verify, you may insert the assersion at more locations and determine which function is the culprit.
> > After locating the function in question, you can make a debug build and use gdb/lldb (any debugger) to step into the C++ code, to see what really happens inside.
> > >
> 
> I wrote a main function(same as the test function test_match_naive_mkl in the validate.py) to test the code running in a pure cpp file (not including pybind). I printed out the status of the matrix allocator and everything is correct(no matter with or without move constructor). Then I use gdb to check the status of matrix_allocator line by line, and the address of matrix_allocator has not changed. There seems to be nothing wrong in a pure cpp environment. Maybe the problem is pybind?
> 

It is possible.  If you do not have a move constructor of Matrix, and you return a Matrix object from C++ to Python using pybind11, it will need to make a copy.

> > This may be memory leak resulted from another test. Maybe your code does not free memory in a correct way when the move constructor is not present.
> > There is no problem in a pure cpp environment.
> 
> Q2
> 
> > The second problem looks like wrong reference to the byte counter. Are you sure you have only one instance of the byte counter?
> 
> Yes, I have only one instance of the byte counter. My global function name bytes() is the same as the member function bytes() in struct MyAllocator. I changed the name of my function, but got the same result. It seems that there is no problem, and I still can't guess where the problem might be.

How do you make sure there is only one instance of the byte counter class?  Have you printed its address?

**Comment by Eric860730** [comment]
> It is possible. If you do not have a move constructor of Matrix, and you return a Matrix object from C++ to Python using pybind11, it will need to make a copy.

Maybe I need to copy or pass my allocator in the Matrix copy constructor?
This is my copy constructor in the Matrix class.

```c++=
 57     Matrix &operator=(Matrix const &other) {
 58       if (this == &other) {
 59         return *this;
 60       }
 61       // check shape
 62       if (m_nrow != other.m_nrow || m_ncol != other.m_ncol) {
 63         reset_buffer(other.m_nrow, other.m_ncol);
 64       }
 65       for (size_t i = 0; i < m_nrow; ++i) {
 66         for (size_t j = 0; j < m_ncol; ++j) {
 67           (*this)(i, j) = other(i, j);
 68         }
 69       }
 70       return *this;
 71     }
```

> How do you make sure there is only one instance of the byte counter class? Have you printed its address?

Maybe I misunderstood what you meant at first. Originally, I checked my source code and only defined a bytes() function. But I do not quite understand you mean. I just used gdb and printed the address of matrix_allocator.counter.m_impl and all the addresses are the same.
This is my gdb print result.

```c++=
(gdb) p matrix_allocator
$14 = {counter = {m_impl = 0x418f20}}
(gdb) p matrix_allocator.counter
$15 = {m_impl = 0x418f20}
(gdb) p matrix_allocator.counter.m_impl
$16 = (ByteCounterImpl *) 0x418f20
(gdb) p *matrix_allocator.counter.m_impl
$17 = {allocated = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 2400}, static is_always_lock_free = true},
  deallocated = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 0}, static is_always_lock_free = true},
  refcount = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 4}, static is_always_lock_free = true}}
```

**Comment by yungyuc** [comment]
> > It is possible. If you do not have a move constructor of Matrix, and you return a Matrix object from C++ to Python using pybind11, it will need to make a copy.
> 
> Maybe I need to copy or pass my allocator in the Matrix copy constructor? This is my copy constructor in the Matrix class.
> 
> ```
>  57     Matrix &operator=(Matrix const &other) {
>  58       if (this == &other) {
>  59         return *this;
>  60       }
>  61       // check shape
>  62       if (m_nrow != other.m_nrow || m_ncol != other.m_ncol) {
>  63         reset_buffer(other.m_nrow, other.m_ncol);
>  64       }
>  65       for (size_t i = 0; i < m_nrow; ++i) {
>  66         for (size_t j = 0; j < m_ncol; ++j) {
>  67           (*this)(i, j) = other(i, j);
>  68         }
>  69       }
>  70       return *this;
>  71     }
> ```
> 

This is the copy assignment operator, not a copy constructor.  Nevertheless, both copy constructor and copy assignment operator, when called, will allocate new memory.  If there is additional copying that is not expected by the test case, the number, you may get your test result:

```
        self.assertEqual(base_alloc + 2*8 * size*size, _matrix.allocated())
E       AssertionError: 640000 != 800000
```

And when you provide the move constructor, pybind11 may use it instead of copy constructor.  The move constructor does not allocate new memory.  That is why I think maybe it's pybind11.

You can verify the theory by comparing the results between the move constructor turned on / off.  In both version, insert a break point in your copy and move constructors and see when pybind11 calls into it.

This is a common workflow of debugging: make a theory and then experiment to verify it, aided by a debugger.  A proficient programmer can complete it in minutes, but if you are not familiar with the task, it is not a problem to use a couple of hours to get used to it (assuming you have the time).

> > How do you make sure there is only one instance of the byte counter class? Have you printed its address?
> 
> Maybe I misunderstood what you meant at first. Originally, I checked my source code and only defined a bytes() function. But I do not quite understand you mean. I just used gdb and printed the address of matrix_allocator.counter.m_impl and all the addresses are the same. This is my gdb print result.
> 
> ```
> (gdb) p matrix_allocator
> $14 = {counter = {m_impl = 0x418f20}}
> (gdb) p matrix_allocator.counter
> $15 = {m_impl = 0x418f20}
> (gdb) p matrix_allocator.counter.m_impl
> $16 = (ByteCounterImpl *) 0x418f20
> (gdb) p *matrix_allocator.counter.m_impl
> $17 = {allocated = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 2400}, static is_always_lock_free = true},
>   deallocated = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 0}, static is_always_lock_free = true},
>   refcount = {<std::__atomic_base<unsigned long>> = {static _S_alignment = 8, _M_i = 4}, static is_always_lock_free = true}}
> ```

Printing the addresses is the right way to check for identity.  Can you do the check in the `Matrix_pybind.cpp` and `_GEMM.cpp` two-file version, at the places the byte counter is used?  My theory is that when you have two compilation units, somehow the compiler creates two instances of the counter and each unit used different one.  An experiment can verify or falsify it.

**Comment by Eric860730** [comment]
> This is the copy assignment operator, not a copy constructor. Nevertheless, both copy constructor and copy assignment operator, when called, will allocate new memory. If there is additional copying that is not expected by the test case, the number, you may get your test result:
> 
> ```
>         self.assertEqual(base_alloc + 2*8 * size*size, _matrix.allocated())
> E       AssertionError: 640000 != 800000
> ```
> 
> And when you provide the move constructor, pybind11 may use it instead of copy constructor. The move constructor does not allocate new memory. That is why I think maybe it's pybind11.
> 
> You can verify the theory by comparing the results between the move constructor turned on / off. In both version, insert a break point in your copy and move constructors and see when pybind11 calls into it.
> 
> This is a common workflow of debugging: make a theory and then experiment to verify it, aided by a debugger. A proficient programmer can complete it in minutes, but if you are not familiar with the task, it is not a problem to use a couple of hours to get used to it (assuming you have the time).

Thank you teacher, I understand.



> Printing the addresses is the right way to check for identity. Can you do the check in the `Matrix_pybind.cpp` and `_GEMM.cpp` two-file version, at the places the byte counter is used? My theory is that when you have two compilation units, somehow the compiler creates two instances of the counter and each unit used different one. An experiment can verify or falsify it.

I set a lot of breakpoints in my_bytes() function in lib/_GEMM.cpp and struct MyAllocator in include/MyAllocator.hpp. It seems that there is only one instance of the counter. It is also possible that I am not familiar with gdb and cannot determine how many instances of the counter have. I have spent several hours on this problem, and I decided to complete my final project first. I think the theory you mentioned is very reasonable. I will come back to study this issue in depth when I have time. Thank you teacher for the guidance and advice. I have learned a lot.

**Comment by yungyuc** [comment]
> > This is the copy assignment operator, not a copy constructor. Nevertheless, both copy constructor and copy assignment operator, when called, will allocate new memory. If there is additional copying that is not expected by the test case, the number, you may get your test result:
> > ```
> >         self.assertEqual(base_alloc + 2*8 * size*size, _matrix.allocated())
> > E       AssertionError: 640000 != 800000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And when you provide the move constructor, pybind11 may use it instead of copy constructor. The move constructor does not allocate new memory. That is why I think maybe it's pybind11.
> > You can verify the theory by comparing the results between the move constructor turned on / off. In both version, insert a break point in your copy and move constructors and see when pybind11 calls into it.
> > This is a common workflow of debugging: make a theory and then experiment to verify it, aided by a debugger. A proficient programmer can complete it in minutes, but if you are not familiar with the task, it is not a problem to use a couple of hours to get used to it (assuming you have the time).
> 
> Thank you teacher, I understand.
> 
> > Printing the addresses is the right way to check for identity. Can you do the check in the `Matrix_pybind.cpp` and `_GEMM.cpp` two-file version, at the places the byte counter is used? My theory is that when you have two compilation units, somehow the compiler creates two instances of the counter and each unit used different one. An experiment can verify or falsify it.
> 
> I set a lot of breakpoints in my_bytes() function in lib/_GEMM.cpp and struct MyAllocator in include/MyAllocator.hpp. It seems that there is only one instance of the counter. It is also possible that I am not familiar with gdb and cannot determine how many instances of the counter have. I have spent several hours on this problem, and I decided to complete my final project first. I think the theory you mentioned is very reasonable. I will come back to study this issue in depth when I have time. Thank you teacher for the guidance and advice. I have learned a lot.

It is a good idea to go back to other work after debugging in a right direction for such long time.  I think you have familiarized yourself with the debugging process and it will be useful in your whole career.

**Pull request merged**
