### PR TITLE
jonathan-liu-0204 Proposal 1st Attempt

### PR DESCRIPTION
**Pull request by jonathan-liu-0204**
---
A good PR should include the following parts:

- [x] A clear title
- [x] A meaningful message for PR, as well as its commits
- [x] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [x] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

### CODE REVIEW

**Review by yungyuc — CHANGES_REQUESTED** [review]
This PR contains unrelated change.  Please fix it before I can further process.

**Comment by jonathan-liu-0204** [comment]
> This PR contains unrelated change. Please fix it before I can further process.

@yungyuc  Just got rid of the unrelated changes, thank you.

**Review by jonathan-liu-0204 — COMMENTED** [review]
@yungyuc  Just got rid of the unrelated changes, thank you.

**Comment by yungyuc** [comment]
> @yungyuc Just got rid of the unrelated changes, thank you.

No you haven't.

**Comment by yungyuc** [comment]
By "changes", I meant git "changeset" or "diff".  You need to get rid of the unwanted "changesets", not to modify to the original contents.

**Pull request closed without merging**
